### ISSUE TITLE
Update in-page navigation on offering pages - Target production no later than 4/6

### ISSUE THREAD

**Issue by actuallyjenn** [GSA/wp2030-microsite#172] opened 2023-01-26 20:18 UTC
The five offering pages should have the updated in-page navigation:

- [x] Update the "title" of the in-page navigation from the offering name to "On this page"
- [x] Enable URL in address bar is updated when navigating the component ([USWDS recently updated this on 3/13](https://github.com/uswds/uswds/pull/5170))

References: https://designsystem.digital.gov/components/in-page-navigation/

**Comment by JessicaMarine1** [comment] 2023-03-08 16:55
@actuallyjenn adding these notes from Wei here for your consideration:
 
- I think those ids with "section_1", "section_2" are auto generated by USWDS in page nav component.
- In our code, I believe we use this line is to add UWWDS in page nav component in, and it will auto generated a tag with id = section_1..etc.



![Image](https://user-images.githubusercontent.com/92383362/223777915-e01fc4da-797b-4499-8207-6af844f6f6c2.png)



![Image](https://user-images.githubusercontent.com/92383362/223777944-a0e8245b-0752-42fb-9db3-fe24dd26e552.png)

**Comment by mark-meyer** [comment] 2023-03-08 17:29
This is hard-coded in the javascript files from USWDS (uswds.js). 

```   
navLinks.setAttribute("href", `#section_${i}`);
navLinks.setAttribute("class", IN_PAGE_NAV_LINK_CLASS);
navLinks.textContent = textContentOfLink;
anchorTag.setAttribute("id", `section_${i}`);
```

Don't the side nav-menus at both https://designsystem.digital.gov/components/side-navigation/ and https://designsystem.digital.gov/components/in-page-navigation/ behave the same as the workplace site?

**Comment by actuallyjenn** [comment] 2023-03-13 13:55
Hmm, yeah, they do. I was torn between the two patterns for the workplace site, but I think the in-page nav works fine. 

I'm wondering if we should change the in-page nav header text to "On this page" instead of the page name since it feels like we've got it floating around in 3 places up top?

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/6501138/224722641-289c4f99-438d-49a6-a81b-6daf3deadd8b.png">

**Comment by lesliel789** [comment] 2023-03-13 17:30
@actuallyjenn I like the idea to have the in-page nav header read "On this page" instead of the page name. Seems like that would help the user.

**Comment by lesliel789** [comment] 2023-03-25 21:59
@actuallyjenn @JessicaMarine1 @mark-meyer  I don't understand the technical notes in this card, but is it possible to update the in-page nav header to "On this page"? If so, are there any more notes needed in this card before it can be moved to ready? I'd like to add this to the next batch if possible. Thanks!

**Comment by actuallyjenn** [comment] 2023-03-27 13:26
We can update the card to reflect that Leslie! I think the rest was my exploration / research and determined that we can use the in-page navigation component, rather than the side navigation, for the site! I'll make the change to the original card and move it.

**Comment by weiwang-gsa** [comment] 2023-03-30 21:14
@actuallyjenn @JessicaMarine1 I just tested to upgrade to USWDS 3.4.1, which they fixed the in-page nav issue. You can view the build here:  https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/wwang-patch-7/offerings/innovation-lab/. 

however, there is new issue after USWDS version upgrade, the GSA Logo text wrapped to 2nd line with version 3.4.1. I report it to USWDS team in slack channel here: https://gsa-tts.slack.com/archives/C3F14AHSQ/p1680208085858799

With this logo text been wrapped to 2nd line issue, and we don't know when this issue will be addressed by USWDS team, do you think we should put in-page nav upgrade on hold or maybe track it in a separate user story?

**Comment by JessicaMarine1** [comment] 2023-03-31 13:20
@weiwang-gsa the first AC (in-page nav header) looks good to me.

@actuallyjenn what do you want to do about the GSA logo text wrapping in the header?

**Comment by actuallyjenn** [comment] 2023-03-31 14:43
woo hoo! this looks great!!

**Comment by SamCioffi** [comment] 2023-03-31 15:49
Thank you! The "On this page" edits look good. However, I noticed the page scroll icon doesn't line up with the headline we're on. Please see the screenshot below; is there a way to fix this? Not sure if its related. @actuallyjenn 

![image](https://user-images.githubusercontent.com/128738447/229168950-be484477-4a3e-408a-89d9-fc6a63dc68a5.png)

**Comment by JessicaMarine1** [comment] 2023-03-31 16:09
@SamCioffi I _believe_ what's happening is "Reserve space to work in our lab" is at the top of your screen, but the following sections (down to and including "Get in touch") are on the screen, so it's highlighting "Get in touch". That is the intended behavior. As you scroll up and down the page, you should see what's highlighted on the in-page nav menu change based on what's displayed on the whole screen.

**Comment by JessicaMarine1** [comment] 2023-03-31 17:12
@SamCioffi this was a bug that you caught!! Way to go, first time Product owner :)

We've elevated the issue to USWDS and will log a _new_ issue to track it's progress to completion. Since the work contemplated in this issue looks good, I'll move this one to DONE.

**Comment by SamCioffi** [comment] 2023-03-31 17:12
You beat me to it @JessicaMarine1 Thank you! Thanks team!

**Comment by SamCioffi** [comment] 2023-03-31 17:14
Just want to give this team a heads up that I will be on leave Monday and Tuesday next week, so I will be able to review and approve any other work from this batch when I get back on Wednesday :)

**Closed** 2023-07-12 16:31 UTC
